name: consume-action
on:
    workflow_dispatch:
jobs:
    consumer:
        runs-on: ubuntu-latest
        steps:
            - name: Demo-ActionLearner
              uses: rudranilgit/testaction@v3.0
              with:
                user-name: "THE BEEKEEPER"