name: Output Demo
on:
    workflow_dispatch:
jobs:
    output_demo:
        runs-on : ubuntu-latest
        outputs:
            user_name: ${{steps.value.outputs.user}}
        steps:
            - name: Set Variable Value
              id: value
              run: echo 'user=RUDRANIL' >> $GITHUB_OUTPUT ';'
            - name: Print Output value
              run: echo "Hello ${{needs.output_demo.outputs.user_name}}".                  