name: ReusableWorkflow
on:
    workflow_call:
        inputs:
            username: 
                description: "The name of the User"
                type:   string
                default: "Rudra"
jobs:
    reusableflow:
        runs-on: ubuntu-latest
        steps:
            - name: Print Hello
              run: echo "HELLO ${{inputs.username}}"        