name: ReusableWorkflow
on:
    workflow_call:
        inputs:
            username: 
                description: "The name of the User"
                type:   string
                default: "Rudra"
                required: true
        secrets:
            ML_PASSWORD:    
                required: true    
        outputs:
            directory: 
                value: ${{jobs.outputs.dir}}
jobs:
    reusableflow:
        outputs:
            dir: ${{steps.getdir.outputs.workingdir}}
        runs-on: ubuntu-latest
        steps:
            - name: Print Hello
              run: echo "HELLO ${{inputs.username}}"
            - name: Get Secrets
              run: echo  "SECRET::${{secrets.ML_PASSWORD}}"   
            - name: Get dir
              id: getdir
              run: |
                working_dir=$(pwd)
                echo "workingdir=$(pwd)" >> $GITHUB_OUTPUT
                echo "$workingdir:::$working_dir"      
            - name: Use the output
              run: |
                echo "The working directory was: ${{ steps.dirval.outputs.workingdir }}"    