name: Demo
on: 
    push:
        paths-ignore:
          - '**.yml'
        branches: [main]
        
        
jobs:
    test_run:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: Install Dependencies
              run:  npm install
            - name: Test Run
              run:  npm test 
    deploy_run:
        needs: test_run
        runs-on: ubuntu-latest
        steps:
            - name: Deploy
              run: echo 'Deploying the code..'        



